version: "3.9"
services:
  server:
    build: ./app
    ports:
      - "8000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
            
  redis:
    image: "redis:alpine"

